import { test } from "node:test";
import assert from "node:assert/strict";

import { formatMarkdown } from "../src/reporters/markdown";
import { formatSarif } from "../src/reporters/sarif";
import { summarizeIssues } from "../src/check";
import type { CheckResult, Issue } from "../src/types";

const issues: Issue[] = [
  {
    type: "missing-key",
    severity: "error",
    locale: "fr",
    key: "a.b",
    file: "locales/en.json",
    line: 3,
    message: 'Key "a.b" is missing in "fr".',
  },
  {
    type: "hardcoded-string",
    severity: "warning",
    file: "src/App.tsx",
    line: 12,
    message: 'Hardcoded JSX text: "Hello"',
  },
];

function resultOf(list: Issue[]): CheckResult {
  return {
    issues: list,
    stats: summarizeIssues(list, { sourceLocale: "en", sourceKeyCount: 10, locales: ["fr"] }),
    missingLocales: [],
  };
}

test("markdown reports failure with an issue table", () => {
  const md = formatMarkdown(resultOf(issues), { toolVersion: "0.1.0" });
  assert.match(md, /## 🌐 LocaleGuard/);
  assert.match(md, /Localization check failed/);
  assert.match(md, /`locales\/en\.json:3`/);
  assert.match(md, /`missing-key`/);
  assert.match(md, /Generated by \[LocaleGuard\].*0\.1\.0/);
});

test("markdown reports a clean pass", () => {
  const md = formatMarkdown(resultOf([]));
  assert.match(md, /All localization checks passed/);
  assert.doesNotMatch(md, /Location/); // no issue table
});

test("sarif is valid 2.1.0 with one result per issue", () => {
  const sarif = JSON.parse(formatSarif(resultOf(issues), { toolVersion: "9.9.9" }));
  assert.equal(sarif.version, "2.1.0");
  const run = sarif.runs[0];
  assert.equal(run.tool.driver.name, "LocaleGuard");
  assert.equal(run.tool.driver.version, "9.9.9");
  assert.equal(run.results.length, 2);

  const first = run.results[0];
  assert.equal(first.ruleId, "missing-key");
  assert.equal(first.level, "error");
  assert.equal(first.locations[0].physicalLocation.artifactLocation.uri, "locales/en.json");
  assert.equal(first.locations[0].physicalLocation.region.startLine, 3);

  // A rule definition exists for every emitted ruleId.
  const ruleIds = new Set(run.tool.driver.rules.map((r: { id: string }) => r.id));
  for (const res of run.results) assert.ok(ruleIds.has(res.ruleId));
});

test("sarif defaults missing line numbers to 1", () => {
  const noLine: Issue = {
    type: "missing-key",
    severity: "error",
    locale: "fr",
    file: "locales/fr",
    message: "No locale files found.",
  };
  const sarif = JSON.parse(formatSarif(resultOf([noLine])));
  assert.equal(sarif.runs[0].results[0].locations[0].physicalLocation.region.startLine, 1);
});
