/**
 * Markdown reporter — designed for a GitHub PR comment or a job summary
 * (`$GITHUB_STEP_SUMMARY`).
 */

import type { CheckResult, Issue } from "../types";

export interface MarkdownReporterOptions {
  /** Tool version to show in the footer. */
  toolVersion?: string;
  /** Maximum number of issue rows to render before truncating. */
  maxRows?: number;
}

export function formatMarkdown(result: CheckResult, opts: MarkdownReporterOptions = {}): string {
  const maxRows = opts.maxRows ?? 50;
  const { stats } = result;
  const out: string[] = [];

  out.push("## 🌐 LocaleGuard");
  out.push("");

  if (result.issues.length === 0) {
    out.push(
      `✅ **All localization checks passed** — \`${stats.sourceLocale}\` reference locale, ` +
        `${stats.sourceKeyCount} keys validated.`,
    );
    out.push("");
    out.push(footer(opts.toolVersion));
    return out.join("\n");
  }

  if (stats.failed) {
    out.push(
      `❌ **Localization check failed** — ${stats.errorCount} error(s), ${stats.warningCount} warning(s).`,
    );
  } else {
    out.push(`⚠️ **Passed with warnings** — ${stats.warningCount} warning(s).`);
  }
  out.push("");

  const summary = summaryParts(result);
  if (summary.length) {
    out.push(summary.join(" · "));
    out.push("");
  }

  out.push("| | Location | Type | Message |");
  out.push("| :-: | --- | --- | --- |");
  for (const issue of result.issues.slice(0, maxRows)) {
    const icon = issue.severity === "error" ? "❌" : "⚠️";
    const where = issue.line ? `\`${issue.file}:${issue.line}\`` : `\`${issue.file}\``;
    out.push(`| ${icon} | ${where} | \`${issue.type}\` | ${escapeCell(issue.message)} |`);
  }
  if (result.issues.length > maxRows) {
    out.push("");
    out.push(`_…and ${result.issues.length - maxRows} more._`);
  }

  out.push("");
  out.push(footer(opts.toolVersion));
  return out.join("\n");
}

function summaryParts(result: CheckResult): string[] {
  const t = result.stats.byType;
  const parts: string[] = [];
  if (t["missing-key"]) parts.push(`**${t["missing-key"]}** missing`);
  if (t["extra-key"]) parts.push(`**${t["extra-key"]}** extra`);
  if (t["placeholder-mismatch"]) parts.push(`**${t["placeholder-mismatch"]}** interpolation`);
  if (t["duplicate-key"]) parts.push(`**${t["duplicate-key"]}** duplicate`);
  if (t["invalid-json"]) parts.push(`**${t["invalid-json"]}** invalid-json`);
  if (t["undefined-key"]) parts.push(`**${t["undefined-key"]}** undefined key`);
  if (t["unused-key"]) parts.push(`**${t["unused-key"]}** unused key`);
  if (t["hardcoded-string"]) parts.push(`**${t["hardcoded-string"]}** hardcoded text`);
  if (t["hardcoded-attribute"]) parts.push(`**${t["hardcoded-attribute"]}** hardcoded attr`);
  return parts;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function footer(version?: string): string {
  const v = version ? ` ${version}` : "";
  return `<sub>Generated by [LocaleGuard](https://github.com/isamrish/localeguard)${v}.</sub>`;
}
